<a href="https://colab.research.google.com/github/averma12/DL-from-scratch/blob/master/Pytorch_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from pathlib import Path
from IPython.core.debugger import set_trace
from fastai import datasets
import pickle,gzip,math,torch,matplotlib as mpl
import matplotlib.pyplot as plt
from torch import tensor

$\triangledown$

In [0]:
def notebook2script(fname):
    fname = Path(fname)
    fname_out = f'nb_{fname.stem.split("_")[0]}.py'
    main_dic = json.load(open(fname,'r'))
    code_cells = [c for c in main_dic['cells'] if is_export(c)]
    module = f'''
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/{fname.name}
'''
    for cell in code_cells: module += ''.join(cell['source'][1:]) + '\n\n'
    # remove trailing spaces
    module = re.sub(r' +$', '', module, flags=re.MULTILINE)
    open(fname.parent/'exp'/fname_out,'w').write(module[:-2])
    print(f"Converted {fname} to {fname_out}")

In [5]:
#element wise operation
a = tensor([10., 6, -4])
b = tensor([2., 8, 7])
a,b

(tensor([10.,  6., -4.]), tensor([2., 8., 7.]))

In [6]:
a<b

tensor([0, 1, 1], dtype=torch.uint8)

In [7]:
a == b

tensor([0, 0, 0], dtype=torch.uint8)

In [8]:
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]]); m

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [10]:
(m*m).sum().sqrt()

tensor(16.8819)

In [15]:
m[1,:] #1st row

tensor([4., 5., 6.])

In [13]:
# Slicing
t = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Every row, only the last column
print(t[:, -1])

# First 2 rows, all columns
print(t[:2, :])

# Lower right most corner
print(t[-1:, -1:])

tensor([3., 6., 9.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[9.]])


In [14]:
torch.cuda.is_available()

False

In [16]:
2*m #broadcasting

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]])

**Broadcasting a vector to a matrix**

In [17]:
c = tensor([10.,20,30]); c

tensor([10., 20., 30.])

In [18]:
m.shape,c.shape

(torch.Size([3, 3]), torch.Size([3]))

In [19]:
m

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [20]:
m + c

tensor([[11., 22., 33.],
        [14., 25., 36.],
        [17., 28., 39.]])

In [21]:
t = c.expand_as(m)
t

tensor([[10., 20., 30.],
        [10., 20., 30.],
        [10., 20., 30.]])

In [22]:
t.storage()

 10.0
 20.0
 30.0
[torch.FloatStorage of size 3]

In [24]:
t.stride(),t.shape

((0, 1), torch.Size([3, 3]))

In [36]:
m.unsqueeze(0),m

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]), tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]))

In [39]:
c.shape,c[None,None,:].shape,c[:,None]

(torch.Size([3]), torch.Size([1, 1, 3]), tensor([[10.],
         [20.],
         [30.]]))

In [44]:
m[1].unsqueeze(-1),m[1,None]

(tensor([[4.],
         [5.],
         [6.]]), tensor([[4., 5., 6.]]))

In [0]:
big_m = tensor([[1,2,1],[0,1,0],[2,3,4]])
small_m = tensor([[2,5],[6,7],[1,8]])

In [51]:
(big_m[1].unsqueeze(-1) * small_m)

tensor([[0, 0],
        [6, 7],
        [0, 0]])

In [54]:
big_m[1].unsqueeze(-1).expand_as(small_m),small_m

(tensor([[0, 0],
         [1, 1],
         [0, 0]]), tensor([[2, 5],
         [6, 7],
         [1, 8]]))

In [0]:
RGB = torch.ones(256,256,3)

In [75]:
type(RGB)

torch.Tensor

In [0]:
scale_up = tensor(20)

In [67]:
scale_up.shape,scale_up

(torch.Size([]), tensor(20))

In [0]:
scale_up_None = scale_up.unsqueeze(-1)

In [0]:
scale_up_2 = tensor([10,20,30])

In [85]:
scale_up_2[None,None,:].expand_as(RGB).float() * RGB

tensor([[[10., 20., 30.],
         [10., 20., 30.],
         [10., 20., 30.],
         ...,
         [10., 20., 30.],
         [10., 20., 30.],
         [10., 20., 30.]],

        [[10., 20., 30.],
         [10., 20., 30.],
         [10., 20., 30.],
         ...,
         [10., 20., 30.],
         [10., 20., 30.],
         [10., 20., 30.]],

        [[10., 20., 30.],
         [10., 20., 30.],
         [10., 20., 30.],
         ...,
         [10., 20., 30.],
         [10., 20., 30.],
         [10., 20., 30.]],

        ...,

        [[10., 20., 30.],
         [10., 20., 30.],
         [10., 20., 30.],
         ...,
         [10., 20., 30.],
         [10., 20., 30.],
         [10., 20., 30.]],

        [[10., 20., 30.],
         [10., 20., 30.],
         [10., 20., 30.],
         ...,
         [10., 20., 30.],
         [10., 20., 30.],
         [10., 20., 30.]],

        [[10., 20., 30.],
         [10., 20., 30.],
         [10., 20., 30.],
         ...,
         [10., 20., 30.],
        

In [82]:
(scale_up_None[None,None,:].expand_as(RGB).float() * RGB.float())

torch.Size([256, 256, 3])

**Einsum examples**

In [87]:
#Transpose
a = torch.arange(6).reshape(2, 3)
torch.einsum('ij->ji', [a]),a

(tensor([[0, 3],
         [1, 4],
         [2, 5]]), tensor([[0, 1, 2],
         [3, 4, 5]]))

In [88]:
#Sum of all elements
a = torch.arange(6).reshape(2, 3)
torch.einsum('ij->', [a])

tensor(15)

In [89]:
#Column sum
a = torch.arange(6).reshape(2, 3)
torch.einsum('ij->j', [a])

tensor([3, 5, 7])

In [90]:
#Row sum
a = torch.arange(6).reshape(2, 3)
torch.einsum('ij->i', [a])

tensor([ 3, 12])

In [91]:
#Matrix vector multiplication
a = torch.arange(6).reshape(2, 3)
b = torch.arange(3)
torch.einsum('ik,k->i', [a, b])

tensor([ 5, 14])

In [92]:
#Matrix matrix multiplication
a = torch.arange(6).reshape(2, 3)
b = torch.arange(15).reshape(3, 5)
torch.einsum('ik,kj->ij', [a, b])

tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])

In [93]:
#Dot product
a = torch.arange(3)
b = torch.arange(3,6)  # -- a vector of length 3 containing [3, 4, 5]
torch.einsum('i,i->', [a, b])

tensor(14)

In [94]:
#Sum of all elements of a matrix
a = torch.arange(6).reshape(2, 3)
b = torch.arange(6,12).reshape(2, 3)
torch.einsum('ij,ij->', [a, b])

tensor(145)

In [95]:
#Element-wise multiplication
a = torch.arange(6).reshape(2, 3)
b = torch.arange(6,12).reshape(2, 3)
torch.einsum('ij,ij->ij', [a, b])

tensor([[ 0,  7, 16],
        [27, 40, 55]])

In [96]:
#Outer product of vectors
a = torch.arange(3)
b = torch.arange(3,7)  # -- a vector of length 4 containing [3, 4, 5, 6]
torch.einsum('i,j->ij', [a, b])

tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])

In [97]:
#Batch Matrix Multiplication
a = torch.randn(3,2,5)
b = torch.randn(3,5,3)
torch.einsum('ijk,ikl->ijl', [a, b])

tensor([[[-1.0730, -2.7480, -0.9323],
         [-1.5748,  4.3495,  0.1762]],

        [[ 0.5835,  2.0364,  0.6670],
         [ 1.3199, -2.4772,  0.7637]],

        [[ 0.6733, -2.2102, -3.7129],
         [-1.7718, -3.3363,  0.1364]]])